name: Rust
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update
      working-directory: src/
      run: cargo update
      #problem with https://github.com/fltk-rs/fltk-rs
